import typing
from MutatorFuzzing.SUTInformation import SUTInformation
from dataclasses import dataclass

@dataclass
class Input:
    info: SUTInformation
    """Summary of some documentation generated by Auto-Prompting LLM"""
    summary: str | None
    """Previous generations, may be used for input mutation, should sensibly implement __repr__"""
    previous_generations: list[typing.Any]
